stages:
  - test

test:stable:
  stage: test
  image: rust:latest
  script:
    - cargo check --release --verbose
    - cargo build --release
    - cargo test --release > /dev/null
    - time cargo test --release

test:nightly:
  stage: test
  image: rustlang/rust:nightly
  script:
    - cargo check --release --verbose
    - cargo build --release
    - cargo test --release > /dev/null
    - time cargo test --release
  allow_failure: true