[package]
name = "project-euler-rust-solutions"
version = "0.1.0"
authors = ["tomitheninja <suditomi@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.fibonacci]
path = "./pkg/fibonacci/"
