[workspace]

members = [
    "collatz_sequence",
    "date",
    "fibonacci_sequence",
    "find_primes",
    "path_sum_triangle",
    "prime_factors",
    "triangular_number_sequence",
    "problems"
]

default-members = [
    "problems"
]