[workspace]
members = [
    "fibonacci-sequence",
    "primes",
    "is-palindrome",
    "p001",
    "p002",
    "p003",
    "p004",
    "p005",
    "p006",
    "p007",
    "p008",
    "p009",
    "p010",
    "p011",
]