[package]
name = "p002"
version = "0.1.0"
authors = ["Südi Tamás <suditomi@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fibonacci-sequence = { path = "../fibonacci-sequence", version = "0" }