[package]
name = "primes"
version = "0.2.0"
authors = ["Südi Tamás <suditomi@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
